develop/community/urls.py
from django.urls import path
from . import views

app_name='community'
urlpatterns = [
    path('', views.board_list, name='board_list'),
    path('write/', views.board_write, name='board_write'),
    path('detail/<int:pk>/', views.board_detail, name='board_detail'),
    path('detail/<int:pk>/delete/', views.board_delete, name='board_delete'),
    path('detail/<int:pk>/modify/', views.board_modify, name='board_modify')
]

develop/config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    # home(main page) -> ex)127.0.0.1:[port]
    path('', views.HomeView, name = 'home'),

    path("admin/", admin.site.urls),
    path("users/",include('users.urls')), 
    path('challenge/', include('challenge.urls')),
    path("exercsie/",include('exercise.urls')),
    path('community/', include('community.urls')),
    path('market/', include('market.urls')), 
    path('mypage/', include('mypage.urls')),
]

# Summernote 설정
from django.conf import settings
from django.conf.urls.static import static

urlpatterns +=[path('summernote/', include('django_summernote.urls'))]

if settings.DEBUG : 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

develop/users/urls.py
from django.urls import path
from . import views
app_name='users'
urlpatterns = [
    path('login/',views.login_view, name='login'),
    path('login/register/',views.register, name='register'),
    path('clear/',views.clear, name='clear'),
    path('login/register/emailvalid/', views.email_validater, name='validation'),
    path('login/register/idvalid/', views.iddupl, name='iddupl'),
    path('login/register/authnumvalid/', views.auth_num_validater, name='authnumval'),
    path('logout/', views.logout, name='logout'),
    path('login/nav_callback/',views.nav_callback, name='nav_callback')
]

develop/community/models.py
from django.db import models
from users.models import Profile

class Board(models.Model) :
    title = models.CharField(max_length=64, verbose_name='글제목')
    contents = models.TextField(verbose_name='글내용')
    writer = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name='작성자')
    write_dttm = models.DateTimeField(auto_now_add=True, verbose_name='글 작성일')

    update_dttm = models.DateTimeField(auto_now=True, verbose_name='마지막 수정일')
    hits = models.PositiveIntegerField(default=0, verbose_name='조회수')

    def __str__(self) : 
        return self.title

    class Meta : 
        db_table = 'board'
        verbose_name = '게시판'
        verbose_name_plural = '게시판'

develop/community/forms.py
from django import forms
from .models import Board
from django_summernote.fields import SummernoteTextField
from django_summernote.widgets import SummernoteWidget

class BoardWriteForm(forms.ModelForm) : 
    title=forms.CharField(
        label = '글제목',
        widget = forms.TextInput(
            attrs={
                'placeholder' : '게시글 제목',
                'input[type="text"]' : {'width' : '80%', 'height' : '30px'}
            }),
        required=True,
    )

    contents = SummernoteTextField()

    field_order = [
        'title',
        'contents'
    ]

    class Meta : 
        model = Board
        fields = [
            'title',
            'contents',
        ]
        widgets = {
            'contents' : SummernoteWidget(attrs={'summernote': {'width': '100%', 'height': '400px', 'resize': 'vertical'}})
        }

    def clean(self):
        cleand_data = super().clean()

        title = cleand_data.get('title', '')
        contents = cleand_data.get('contents', '')

        if title == '' :
            self.add_error('title', '글 제목을 입력하세요.')
        elif contents == '':
            self.add_error('contents', '글 내용을 입력하세요')
        else : 
            self.title = title
            self.contents = contents

develop/community/views.py
import profile
from django.shortcuts import render, redirect,  get_object_or_404
from .forms import BoardWriteForm 
from .models import Board
from users.models import Profile
from users.decorators import login_required
from datetime import date, datetime, timedelta
from .pagination import pagination

# 게시판
def board_list(request):
    login_session = request.session.get('user')
    context = {'login_session' : login_session}

    boards = Board.objects.all().order_by('-id')
    page = pagination(request, Board)
    hits_boards = Board.objects.all().order_by('-hits')

    if login_session != None:
            user=Profile.objects.get(id=login_session)
            context={'user_name':user.user_name}
            context['boards'] = boards
            context['hits_boards'] =hits_boards[0:3]
            context.update(page)
            return render(request,'community/board_list.html',context)
            
    if login_session == None:
            context['boards'] = boards
            context['hits_boards'] =hits_boards[0:3]
            context.update(page)
            return render(request,'community/board_list.html',context)

# 게시글 보기
def board_detail(request, pk) :
    login_session = request.session.get('user')
    context = {'login_session' : login_session}

    board = get_object_or_404(Board, id=pk)

    if login_session != None :
        user=Profile.objects.get(id=login_session)
        context={'user_name':user.user_name}
        context['board'] = board
        
        if board.writer.user_id == user.user_id:
            context['writer'] = True
        else :
            context['writer'] = False

        response = render(request,'community/board_detail.html',context)
            
    if login_session == None:
        context['board'] = board
        response = render(request,'community/board_detail.html',context)

    # 조회수
    expire_date, now = datetime.now(), datetime.now()
    expire_date += timedelta(days=1)
    expire_date =expire_date.replace(hour=0, minute=0, second=0, microsecond=0)
    expire_date -= now
    max_age = expire_date.total_seconds()

    cookie_value = request.COOKIES.get('hitsboard', '_')

    if f'_{pk}_' not in cookie_value :
        cookie_value += f'{pk}_'
        response.set_cookie('hitboard', value=cookie_value, max_age=max_age, httponly=True)
        board.hits +=1
        board.save()
    
    return response

# 게시글 쓰기
@login_required
def board_write(request):
    login_session = request.session.get('user')
    context = {'login_session' : login_session}

    if request.method =='GET' :
        write_form = BoardWriteForm()
        context['forms'] = write_form
        return render(request, 'community/board_write.html', context)

    elif request.method == 'POST':
        write_form = BoardWriteForm(request.POST)

        if write_form.is_valid():
            writer = Profile.objects.get(id = login_session)
            board = Board(
                title = write_form.title,
                contents = write_form.contents,
                writer = writer,
            )
            board.save()
            return redirect('/community')
        else : 
            context['forms']= write_form
            if write_form.errors : 
                for value in write_form.errors.values():
                    context['error'] = value
                return render(request, 'community/board_write.html', context)

# 게시글 삭제
def board_delete(request, pk):
    login_session = request.session.get('user')
    board = get_object_or_404(Board, id=pk)

    if login_session != None :
        user=Profile.objects.get(id=login_session)

        if board.writer.user_id == user.user_id:
            board.delete()
            return redirect('/community')
        else : 
            return redirect(f'community/detail/{pk}/')

# 글 수정
@login_required
def board_modify(request, pk) : 
    login_session = request.session.get('user')
    context = {'login_session' : login_session}

    board = get_object_or_404(Board, id=pk)
    context['board'] = board

    if login_session != None :
        user=Profile.objects.get(id=login_session)

        if board.writer.user_id != user.user_id:
            return redirect(f'community/detail/{pk}/')

        if request.method == 'GET' : 
            write_form = BoardWriteForm(instance=board)
            context['forms'] = write_form
            return render(request, 'community/board_modify.html', context)

        elif request.method =='POST' :
            write_form = BoardWriteForm(request.POST)

            if write_form.is_valid() : 
                board.title = write_form.title
                board.contents = write_form.contents

                board.save()
                return redirect('/community')
            
            else :
                context['forms'] = write_form
                if write_form.errors :
                    for value in write_form.errors.values():
                        context['error'] = value
                return render(request, 'community/board_modify.html', context)

develop/templates/community/board_detail.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" href="{% static 'community/board_detail.css' %}">
        <title>Community</title>
    </head>
    <body>
        <header>
            <div class = "wrapper">
                <h1>
                    <a href="{% url 'home'%}">HealF </a>
                </h1>
                <ul class = "menu">
                    {% if user_name != anonymous %}
                    <li>{{user_name}}님 접속을 환영합니다.</li>
                    <li><a href="{% url 'users:logout'%}">로그아웃</a></li>
                    {% else %}
                    <li><a href="{% url 'users:login'%}">로그인</a></li>
                    <li><a href="{% url 'users:register'%}">회원가입</a></li>
                    {% endif %}
                </ul>
            </div>
        </header>
        <div class="board_wrap">
            <div class="board_view">
                <div class="title">
                    <strong>{{board.title}}</strong>
                    <div class="date">{{board.write_dttm}}</div>
                </div>
                <div class="info">
                    <dl>
                        <dt>글쓴이</dt>
                        <dd>{{board.writer}}</dd>
                    </dl>
                    <dl>
                        <dt>조회</dt>
                        <dd>{{board.hits}}</dd>
                    </dl>
                </div>
                <div class="cont">
                    {{board.contents|safe}}
                </div>
            </div>
            <div class="button">
                <a href="{% url 'community:board_list' %}">목록</a>
                {% if writer %}
                <a href="/community/detail/{{ board.id }}/delete">삭제</a>
                <a href="/community/detail/{{ board.id }}/modify">수정</a>
                {% endif %}
            </div>
        </div>
    </body>
</html>

develop/templates/community/board_list.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8">    
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" href="{% static 'community/board_list.css' %}">

        <title>Community</title>
    </head>
    <body>
        <header>
            <div class = "wrapper">
                <h1>
                    <a href="{% url 'home'%}">HealF </a>
                </h1>
                <ul class = "menu">
                    {% if user_name != anonymous %}
                    <li>{{user_name}}님 접속을 환영합니다.</li>
                    <li><a href="{% url 'users:logout'%}">로그아웃</a></li>
                    {% else %}
                    <li><a href="{% url 'users:login'%}">로그인</a></li>
                    <li><a href="{% url 'users:register'%}">회원가입</a></li>
                    {% endif %}
                </ul>
            </div>

        </header>
        <div class="board_wrap">
            <div class="info">
                <div class="name">
                    <strong>community</strong><br> 
                </div>
            </div>
            <div class="board">
                <div class="top">
                    <div class="num">번호</div>
                    <div class="title">제목</div>
                    <div class="writer">작성자</div>
                    <div class="date">날짜</div>
                    <div class="count">조회수</div>
                </div>
                {%  for board in hits_boards %}
                {% if board %}
                <div style="background-color:beige">
                    <div class="num"><image style="width:30%; height:30%; margin-top:-10%;margin-bottom:-10%" src="{% static 'community/hot2.png' %}"/></div>
                    <div class="title">
                        <a href="/community/detail/{{board.id}}" target="_self">
                            {{ board.title }}
                        </a></div>
                    <div class="writer">{{ board.writer }}</div>
                    <div class="date">{{ board.write_dttm |date:'Y.m.d' }}</div>
                    <div class="count">{{ board.hits }}</div>
                </div>
                {% endif %}
                {% endfor %}


                {%  for board in boards %}
                {% if board %}
                <div>
                    <div class="num">{{ board.id }}</div>
                    <div class="title">
                        <a href="/community/detail/{{board.id}}" target="_self">
                            {{ board.title }}
                        </a></div>
                    <div class="writer">{{ board.writer }}</div>
                    <div class="date">{{ board.write_dttm |date:'Y.m.d' }}</div>
                    <div class="count">{{ board.hits }}</div>
                </div>
                {% endif %}
                {% endfor %}
            </div>

            <div class="button_page">

                <a href="?page=1"><<</a>

                {% if active_previous_page_chunk %}
                <a href="?page={{ previous_page_cunk }}"><</a>
                {% else %}
                <a href="#"><</a>
                {% endif %}

                {% for key, value in display_page.items %}
                {% if value %}
                {% if value == now_page %}
                <a href="?page={{ value }}" class="num">{{ value }}</a>
                {% else %}
                <a href="?page={{ value }}">{{ value }}</a>
                {% endif %}
                {% endif %}
                {% endfor %}

                {% if active_next_page_chunk %}
                <a href="?page={{ next_page_cunk }}">></a>
                {% else %}
                <a href="#">></a>
                {% endif %}

                <a href="?page={{ end_page }}">>></a>

            </div>
            <div class="button">
                <a href="{% url 'community:board_write' %}">글작성</a>
            </div>
        </div>
        <footer>
            <div class="container">
                <a href="{% url 'home'%}">2022 HealF</a>
                <h6>Copyright © HealF Inc. All rights reserved.</h6>
            </div>
        </footer>
        
    </body>
</html>

develop/templates/community/board_modify.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" href="{% static 'community/board_write.css' %}">
        <title>Community</title>
    </head>
    <body>
        <header>
            <div class = "wrapper">
                <h1>
                    <a href="{% url 'home'%}">HealF </a>
                </h1>
            </div>
        </header>

        <div class="board_wrap">
            <div class="info">
                <div class="name">
                    <strong>글수정</strong> 
                </div>
            </div>
            <form action="" method="POST">
                {% csrf_token %}
            
                {% for form in forms %}
                <div>
                    <label for="{{ form.id_for_label}}">{{form.label}}</label>
                    {{form}}
                </div>
                {% endfor %}
            
                {% if error %}
                {{ error }}
                {% endif %}
            
                <button type="submit">수정하기</button>
            </form>
        </div>
    </body>
</html>

develop/templates/community/board_write.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" href="{% static 'community/board_write.css' %}">
        <title>Community</title>
    </head>
    <body>
        <header>
            <div class = "wrapper">
                <h1>
                    <a href="{% url 'home'%}">HealF </a>
                </h1>
            </div>
        </header>

        <div class="board_wrap">
            <div class="info">
                <div class="name">
                    <strong>글작성</strong> 
                </div>
            </div>
            <div class="board_write">
                <form action="{% url 'community:board_write' %}" method="POST">
                    {% csrf_token %}
                
                    <div class="title">
                        <dl>
                            <dt>제목</dt>
                            <dd>{{forms.title}}</dd>
                        </dl>
                    </div>

                    {{forms.contents}}

                    {% if error %}
                    {{ error }}
                    {% endif %}
                
                    <div class="button">
                        <button type="submit" id="write">작성하기</button>
                    </div>
                </form>
                
                <div class="contents">
                </div>
            </div>
        </div>
    </body>
</html>