develop/mypage/urls.py
from django.urls import path
from . import views

app_name = 'mypage'

urlpatterns=[
    path('',views.mypageView,name='mypage_view'),
    path('update/',views.update,name='update'),
]

develop/mypage/models.py
from django.db import models

# Create your models here.

develop/mypage/views.py
from django.shortcuts import render,redirect
from django.views.generic import TemplateView
from users.models import Profile
from market.models import Item
from community.models import Board
from challenge.models import Count_Post

def mypageView(request):
    current_id = request.session.get('user')
    if current_id is None: 
            return render(request, 'users/login.html', {'prev_path':request.path})
    Profile_info=Profile.objects.get(id=current_id)
    print(Profile_info.user_image)
    Item_info=Item.objects.filter(user_info=current_id)
    Board_info=Board.objects.filter(writer= current_id)
    Count_Post_info=Count_Post.objects.filter(user_info= current_id)
    context={'Profile_info':Profile_info,'Item_info':Item_info,'Board_info':Board_info,
        'Count_Post_info':Count_Post_info}

    return render(request, 'mypage.html', context)
class Profile_update():
    def __init__(self,request):
        self.current_id = request.session.get('user')

def update(request):
    current_id = request.session.get('user')
    print(request.method)
    if request.method == "GET":
        Profile_info=Profile.objects.get(id=current_id)
        context={'Profile_info':Profile_info}
        return render(request,'update.html',context)
    elif request.method == "POST":
        imgs=request.FILES.get('input_image')
        print(imgs)
        Profile_info=Profile.objects.get(id=current_id)
        Profile_info.user_image=imgs
        Profile_info.save()
    return redirect("mypage:mypage_view")

# Create your views here.
# class mypageClass():#객체지향 따라해보기-모델들의 외래키 이름이 모두 다르기 때문에 폐기
#     def __init__(self, request):#mypageClass의 생성자. current_id를 변수로 갖는 인스턴스 생성  
#         self.current_id = request.session.get('user')
#     def get(self,model):#모델명을 선택하면 id가 일치하는 object들을 모두 획득한다.
#         try: 
#             self.get_object = model.objects.filter(id=Profile.self.current_id)
#         except:
#             self.get_object = None
#         return self.get_object

# def mypageView(request):
#     info=mypageClass(request) #mypageClass의 생성자 호출
#     if info.current_id is None: 
#             return render(request, 'users/login.html', {'prev_path':request.path})
#     Profile_info=info.get(Profile)#get함수를 재활용
#     Item_info=info.get(Item)
#     Board_info=info.get(Board)
#     Count_Post_info=info.get(Count_Post)
#     print(Item_info)
#     context={'Profile_info':Profile_info,'Item_info':Item_info,'Board_info':Board_info,
#         'Count_Post_info':Count_Post_info}

#     return render(request, 'mypage.html', context)

develop/mypage/templates/mypage.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <link rel="stylesheet" href="{% static 'mypage/mypage.css' %}">
    <title>mypage</title>
</head>


<body>
    <header>
        <div class="wrapper">
            <h1>
                <a href="{% url 'home' %}">HealF </a>
            </h1>
        </div>
    </header>
    <div class="info">
        <div class="top_title">
            mypage
        </div>
        <div id="date" class="date">
        </div>
    </div>


        <div class="page_wrap">
            <ul class="cards">
                <li>
                    <div class="card">
                        {% if Profile_info.user_background is not exist %}
                            <img src="{% static 'mypage/프로필.jfif' %}" class="card__image" alt="" />
                        {% else %}
                            <img src="{{Profile_info.user_background.url}}" class="card__image" art="" />
                        {% endif %}
                        <div class="card__overlay">
                            <div class="card__header">
                                <svg class="card__arc" xmlns="http://www.w3.org/2000/svg">
                                    <path />
                                </svg>
                                {% if Profile_info.user_image == none %}
                                    <img class="card__thumb" src="{% static 'mypage/no-image.png' %}" alt=""/>
                                {% else %}
                                    <img class="card__thumb" src="{{Profile_info.user_image.url}}" alt="" />
                                {% endif %}
                                <div class="card__header-text">
                                    <h3 class="card__title">{{Profile_info.user_name}}</h3>
                                    <span class="card__status">{{Profile_info.user_id}}</span>
                                    <a href="{% url 'mypage:update' %}"><h6 class="card__status">프로필 수정</h6></a>
                                </div>

                                
                                <div class = "card__thumb_manner_text">
                                    <img class="card__thumb_manner" src="{% static 'mypage/happy.png' %}" alt="" />
                                    <h3>99도</h3>
                                </div>

                                
                            
                            </div>
                            <p class="card__description"> 나의 운동 정보 > {{Count_Post_info.user_count}}<br>
                                나의 활동 분석 > {{Count_Post_info.user_confirm}}<br></p>
                        </div>
                    </div>
                </li>
            </ul>
    
            <!--
            <div class="profile_wrap">
                <p>정보 수정하기</p>
                <div class="profile">
                    <div class="me">
                        내 프로필<br>
                        <img src="./프로필.jfif">
                    </div>
                    <div class="else">
                        <span>오리꽥 님</span><br>
                        ohyunha1576<br>
                        나의 운동 정보 ><br>
                        나의 활동 분석 ><br>
                    </div>
                </div>
            </div>
            !-->


            <div class="page_wrap">
                <ul class="cards">
                    <li>
                        <a href="" class="card">
                            <img src="{% static 'mypage/mainPic.jpg' %}" class="card__image" alt="" />
                            <div class="card__overlay">
                                <div class="card__header">
                                    <svg class="card__arc" xmlns="http://www.w3.org/2000/svg">
                                        <path />
                                    </svg>
                                    <img class="card__thumb" src="https://i.imgur.com/7D7I6dI.png" alt="" />
                                    <div class="card__header-text">
                                        <h3 class="card__title">내 운동+</h3>
                                    </div>
                                </div>
                                <p class="card__description"> 팔굽혀 펴기 3일전<br>
                                    윗몸 일으키기 4일전<br></p>
                            </div>
                        </a>
                    </li>
                </ul2>

            <!--
            <div class="health_wrap">
                <div class="page_wrap">


                    <div class="title">내 운동+</div>
                    <div class="info">
                        <div class="recent">최근 참여</div>
                        <ul>
                            <li>팔굽혀펴기 <span>3일전</span></li>
                            <li>윗몸일으키기 <span>15일전</span></li>
                        </ul>
                    </div>
                </div>
            </div> 
        -->

        <table>
            <thead>
            <tr>
                <th style="text-align: center;">닉네임</th>
                <th style="text-align: center;">운동종류</th>
                <th style="text-align: center;">순위</th>
                <th sty>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td style="text-align: center;">오리꽥님</td>
                <td style="text-align: center;">스쿼트</td>
                <td style="text-align: center;">1 등</td>
                
            </tr>
            <tr>
                <td style="text-align: center;">오리꽥님</td>
                <td style="text-align: center;">푸쉬업</td>
                <td style="text-align: center;">3등</td>
           
            </tr>
          
            </tbody>
        </table>
        

                <div class="market_wrap" style="width: 77%; margin-top: 13%; box-shadow: 0 4px 7px rgba(0,0,0,.25); background-color: white;">

                    <!-- <div class="title">내 거래 물건 +</div> -->
                    <div class="title">
                        <h3 style="font-size:20px; color: white"; >내 거래 물건 +</h3>
                    </div>

                    <div class="info">
                        <button class="판매내역"><span>판매내역</span></button>
                        <button class="구매내역" style="margin-left: 5%;"><span>구매내역</span></button>
                    </div>
                
                    <div class="info_card" style="display:flex">
                        {% for item in Item_info %}
                            <div><a href="{{ item.get_absolute_url }}"><img src = 'https://user-images.githubusercontent.com/54762273/179995513-dd8cb2b2-d968-4d47-b4f9-5994a0a6b29d.png'>
                            <h3>{{ item.title }}</h3></a>
                            </div>
                        {% endfor %}
                    </div>

                </div>
            </div>
            <div class="page_wrap">
                <div class="market_wrap" style="width: 77%; margin-top: 13%; box-shadow: 0 4px 7px rgba(0,0,0,.25); background-color: white;">

                    <!-- <div class="title">내 거래 물건 +</div> -->
                    <div class="title">
                        <h3 style="font-size:20px; color: white"; >내 거래 물건 +</h3>
                    </div>

                    <div class="info">
                        <button class="판매내역"><span>내가 쓴 글</span></button>
                        <button class="구매내역" style="margin-left: 5%;"><span>내가 단 댓글</span></button>
                    </div>
                
                    <div class="info_card">
                        {% for board in Board_info %}
                            <div><a href="{{ board.get_absolute_url }}">
                            <h3>{{ board.title }}</h3></a>
                            </div>
                        {% endfor %}
                    </div>

                </div>
            </div>
        </div>
        <script>
            let day = new Date();
            document.getElementById('date').innerHTML = "TODAY " + day.getFullYear() + "/" + parseInt(day.getMonth() + 1) + "/" + day.getDate();
        </script>
</body>

</html>

develop/mypage/templates/update.html
{% load static %}
<html>
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
        <title>프로필 수정</title>
        <script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <link rel = "stylesheet" href ="{% static 'mypage/update.css' %}">
    </head>

    <body>
        <header>
            <div class = "wrapper">
                <h1>
                <a href="{% url 'home' %}">HealF </a>
                </h1>
            </div>
        </header>
        <div class="wrap">
            <form method="post" id="form" action="{% url 'mypage:update' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <div id="content">
                    <div class="box">
                        {% if Profile_info.user_image is not exist %}
                            <span><img style="width:50px" src="{% static 'mypage/no-image.png' %}" alt=""/>
                        {% else %}
                            <img src="{{Profile_info.user_image.url}}" alt="" />
                        {% endif %}
                        <label for="input_image" >변경</label>
                        <input type="file" id="input_image" name="input_image" style="display:none">
                        </span>
                    </div>
                    <div class="box">
                        <div>{{Profile_info.user_background}}</div>
                        <label for="input_image" ></label>
                        <input type="file" style="display:none" multiple>
                    </div>
                    <div class="box">

                        <label for="id_update" >아이디</label>
                        <h3>{{Profile_info.user_id}}</h3>
                        <button style="height:30px">변경</button>
                    </div>
                    <div class="box">
                    <span>
                        <label for="id_update" >이름</label>
                        <h3>{{Profile_info.user_name}}</h3>
                        </span>
                    </div>
                    
                </div>
                <div><input type="submit"> </div>
            </form>
        </div>
    </body>