django_an/HealF/urls.py
# HealF application에 config 프로젝트와 연결된 urls.py파일 생성

from django.urls import path
from . import views

app_name = 'HealF'
urlpatterns = [
    # --------------- main page --------------
    
    # /HealF/
    path('', views.HealFMainView.as_view() , name = 'main'),
    # /HealF/challenge
    path('challenge/', views.HealFchallengeView.as_view(), name = 'challenge'),
    # /HealF/exercise
    path('exercise/', views.HealFexerciseView.as_view(), name= 'exercise'),
    # /HealF/community
    path('community/', views.HealFcommunityView.as_view(), name = 'community'),
    # /HealF/market
    path('market/', views.HealFmarketView.as_view(), name='market'),
    # /HealF/mypage
    path('mypage/', views.HealFmypageView.as_view(), name='mypage'),

    # --------------- login & sign-up page --------------
    path('login/', views.HealFloginView.as_view(), name = 'login'),
    path('sign-up/', views.HealFsignupView.as_view(), name = 'sign-up'),

    # --------------- challenge page --------------
    path('challenge/exercise/', views.Challenge_exerciseView.as_view(), name = 'challenge_exercise'),
    path('challenge/diet/', views.Challenge_dietView.as_view(), name = 'challenge_diet'),

    # --------------- market page --------------
    path('market/product/', views.MkarketproductView.as_view(), name = 'market_product'),

]

django_an/config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include # HealF application의 url과 연동을 시키기 위해 include 함수 사용

urlpatterns = [
    path('admin/', admin.site.urls),
    path('HealF/', include('HealF.urls')),   # HealF application의 urls.py 파일 연결
    path('openpose/', include('openpose.urls')), # openpose application 연결
    path('markets/', include('markets.urls')), # markets application 연결
]

django_an/HealF/views.py
from django.shortcuts import render

from django.views.generic import TemplateView

#- TemplateView 이용 -> template 파일만을 렌더링하는 경우에 사용


# ------------------ main page ------------------------

class HealFMainView(TemplateView):
    template_name = 'main/main.html'

    def get(self, request, *args, **kwargs):
        ctx = {}                             # 템플릿에 전달할 데이터
        return self.render_to_response(ctx)

class HealFchallengeView(TemplateView):
    template_name = 'challenge/challenge.html' # 챌린지 메인 화면

    def get(self, request, *args, **kwargs):
        ctx = {}                             
        return self.render_to_response(ctx)

class HealFexerciseView(TemplateView):
    template_name = 'exercise/exercise.html' # 운동 메인 화면

    def get(self, request, *args, **kwargs):
        ctx = {}                             
        return self.render_to_response(ctx)

class HealFcommunityView(TemplateView):
    template_name = 'community/commu.html' # 커뮤니티 화면

    def get(self, request, *args, **kwargs):
        ctx = {}                             
        return self.render_to_response(ctx)

class HealFmarketView(TemplateView):
    template_name = 'market/market.html' # 마켓 화면

    def get(self, request, *args, **kwargs):
        ctx = {}                             
        return self.render_to_response(ctx)

class HealFmypageView(TemplateView):
    template_name = 'mypage/mypage.html' # 나의정보 화면

    def get(self, request, *args, **kwargs):
        ctx = {}                             
        return self.render_to_response(ctx)


# ------------------ login & sign-up page ------------------------

class HealFloginView(TemplateView):
    template_name = 'login/login.html' # login 화면

    def get(self, request, *args, **kwargs):
        ctx = {}                             
        return self.render_to_response(ctx)

class HealFsignupView(TemplateView):
    template_name = 'login/signup.html' # sign-up 화면

    def get(self, request, *args, **kwargs):
        ctx = {}                             
        return self.render_to_response(ctx)


# ------------------ challenge page ------------------------

class Challenge_exerciseView(TemplateView):
    template_name = 'challenge/challenge_exercise.html' # challege화면의 운동하기 화면

    def get(self, request, *args, **kwargs):
        ctx = {}                             
        return self.render_to_response(ctx)

class Challenge_dietView(TemplateView):
    template_name = 'challenge/challenge_diet.html' #challenge화면의 다이어트하기 화면

    def get(self, request, *args, **kwargs):
        ctx = {}                             
        return self.render_to_response(ctx)


# ------------------ market page ------------------------

class MkarketproductView(TemplateView):
    template_name = 'categorie/categorie.html' # market 화면의 제품 화면

    def get(self, request, *args, **kwargs):
        ctx = {}                             
        return self.render_to_response(ctx)

django_an/HealF/templates/main/main.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="utf-8"/>
    <meta name="keywords" content=""> <!--검색엔진 키워드-->
    <meta name="description" content=""> <!--홈페이지 설명-->
    <title>헬스 친구 HealF</title>
    <!-- css -->
    <link rel="stylesheet" href="{% static 'main/main.css' %}">
    <!-- <link rel = "stylesheet" href="main.css"> -->

  </head>
  <body>
    <!-- header -->
    <header>
      <div class = "wrapper">
        <h1>
          <!-- url을 설정할 때 HealF 앱의 url을 명시해주어야 한다. -->
          <a href="{% url 'HealF:main' %}">HealF</a>  
        </h1>
        <ul class = "menu">
          <li><a href="{% url 'HealF:login' %}">로그인</a></li>
          <li><a href="{% url 'HealF:sign-up' %}">회원가입</a></li>
        </ul>
      </div>
    </header>
    <!--어플 다운로드 링크-->
    <div class = "appdown">
       <a href="#" calss = "android" target="blank" title="구글플레이 다운로드">
         <img src="/static/main/사진/앱다운로드.png" alt="앱 다운로드 하기">
       </a>
    </div>
    <!--main 설명-->
    <div class = "main">
      <div class = "titlewrapper">
      <h3>Health Friends</h3>
      <p>대한민국 1위 헬스 플랫폼</p>
    </div>
    </div>
    <!--바로가기-->
    <div class = "link">
      <a href="{% url 'HealF:exercise' %}">
        <img src="/static/main/사진/운동하기.png"><p>운동하기</p>
      </a>
      <a href="{% url 'HealF:challenge' %}">
        <img src="/static/main/사진/챌린지.png"><p>챌린지</p>
      </a>
      <a href="{% url 'HealF:community' %}">
        <img src="/static/main/사진/커뮤니티.png"><p>커뮤니티</p>
      </a>
      <a href="{% url 'HealF:market' %}">
        <img src="/static/main/사진/마켓.png"><p>마켓</p>
      </a>
      <a href="{% url 'HealF:mypage' %}">
        <img src="/static/main/사진/나의 정보.png"><p>나의 정보</p>
      </a>
    </div>
    <!--footer-->
    <footer>
    </footer>
  </body>
</html>